services:
  - type: web
    name: hinglish-tts-app
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MURF_API_KEY
        sync: false
      - key: PORT
        value: 10000 